Create employee user
TreinaDev/GestaoEmpresasTD10 pull request #13
Opened 2023-06-08 14:14 UTC by leanddro

- Criação de funcionário a partir de um CPF pre cadastrado na tabela de employee.
- Automatização  definição de role do user seguindo as regras de negocio.

2023-06-09 13:54 UTC, joaorsalmeida requested changes

2023-06-09 13:54 UTC, joaorsalmeida commented on spec/models/company_spec.rb
> +      Company.create!(brand_name: 'Campus Code', corporate_name: 'Campus Code Treinamentos LTDA',
Aqui só tem teste de erro né? Poderia ter um teste de sucesso, que a empresa é criada normalmente.

2023-06-09 13:54 UTC, joaorsalmeida commented on spec/system/company/admin_register_a_company_spec.rb
> +# TODO: Alterar a navegação após a criação dos menus e links
Já comentei em outro MR, mas removam esse comentário e transformem num item de backlog.

2023-06-09 13:54 UTC, joaorsalmeida commented on app/views/devise/shared/_links.html.erb
> +  <%= link_to "Log in", new_session_path(resource_name) %><br />
Bora traduzir todos estes arquivos?

2023-06-09 19:45 UTC, renan-ras commented on spec/models/company_spec.rb
> +      Company.create!(brand_name: 'Campus Code', corporate_name: 'Campus Code Treinamentos LTDA',
Criado teste de sucesso com duas empresas.

2023-06-09 19:45 UTC, renan-ras commented on spec/system/company/admin_register_a_company_spec.rb
> +# TODO: Alterar a navegação após a criação dos menus e links
Comentários removidos e inseridos no backlog.

2023-06-09 19:50 UTC, renan-ras commented on app/views/devise/shared/_links.html.erb
> +  <%= link_to "Log in", new_session_path(resource_name) %><br />
Traduzidos!

2023-06-12 19:24 UTC, akaninja commented
Pessoal, reparei que vários PRs estão mostrando vários commits iguais e as changes apresentadas ficam iguais também. Isso deixa a revisão do código impossível. Seria bom isso ser corrigido. Cada PR deve mostrar somente o código referente a funcionalidade que está sendo implementada no PR específico.

2023-06-13 14:51 UTC, renan-ras commented
Nova branch criada, apenas com código da funcionalidade.

2023-06-13 14:51 UTC, closed without merging