Login nav view
TreinaDev/GestaoEmpresasTD10 pull request #25
Opened 2023-06-15 19:37 UTC by tecnodiniz

Layout de da tela de login e nav-var(menu) da aplicação criado. 

Segue os prints das telas:

OBS: Colocamos o login para ser obrigatório ao iniciar a aplicação. 

![Captura de tela de 2023-06-15 16-33-39](https://github.com/TreinaDev/GestaoEmpresasTD10/assets/73700400/5eeb7001-fa73-48d3-82d4-d86207e81f4e)
![Captura de tela de 2023-06-15 16-33-52](https://github.com/TreinaDev/GestaoEmpresasTD10/assets/73700400/28bdc0cd-94e8-4b85-9158-dcb955b75293)
![Captura de tela de 2023-06-15 16-34-08](https://github.com/TreinaDev/GestaoEmpresasTD10/assets/73700400/c6964c47-c835-4fda-87b3-3d392e531301)

2023-06-16 00:55 UTC, BrunoSGuima commented on spec/system/user_visit_homepage_spec.rb
Porque não remove esse teste?

2023-06-16 01:11 UTC, BrunoSGuima approved these changes
Acho que podem remover o teste 'Visitante navega pela app' já que estão fazendo a homepage. E também para evitarmos testes comentados na main.

2023-06-16 01:20 UTC, BrunoSGuima requested changes
Não seria bom fazer testes verificando que todos os link_to e button_to que vocês colocaram na tela inicial, estão lá e funcionando como esperado?

2023-06-16 03:03 UTC, renan-ras commented on app/views/layouts/application.html.erb
> +                <%# Se admin:
Já podem remover esse comentário?

2023-06-16 03:05 UTC, renan-ras commented on app/views/layouts/application.html.erb
A navegação do manager e funcionário não será implementada?

2023-06-16 17:28 UTC, tecnodiniz commented on spec/system/user_visit_homepage_spec.rb
Vamos remover.

2023-06-16 17:28 UTC, tecnodiniz commented
> Não seria bom fazer testes verificando que todos os link_to e button_to que vocês colocaram na tela inicial, estão lá e funcionando como esperado?

Boa idea

2023-06-16 17:29 UTC, tecnodiniz commented on app/views/layouts/application.html.erb
> +                <%# Se admin:
Já! hahaha

2023-06-16 17:30 UTC, tecnodiniz commented on app/views/layouts/application.html.erb
Se for a questão dos links aparecem de acordo com a role, sim, já está implementada

2023-06-16 20:50 UTC, BrunoSGuima commented on spec/system/navbar/admin_see_navbar_spec.rb
> +feature 'administrador entra no sisetma' do
Erro de português no "sisetma".

2023-06-16 20:51 UTC, BrunoSGuima commented on spec/system/navbar/admin_see_navbar_spec.rb
> +  scenario 'e vê os items estilizados do navbar' do
Items está em inglês. "Itens" em português.

2023-06-16 20:53 UTC, BrunoSGuima commented on spec/system/navbar/admin_see_navbar_spec.rb
> +    scenario 'de cadastra empresa' do
"de cadastrar empresas"

2023-06-16 20:54 UTC, BrunoSGuima commented on spec/system/navbar/manager_see_navbar_spec.rb
> +feature 'manager entra no sisetma' do
Erro de português no "sisetma".

2023-06-16 20:55 UTC, BrunoSGuima commented on spec/system/navbar/manager_see_navbar_spec.rb
> +  scenario 'e não vê os items do administrador' do
Items está em inglês. "Itens" em português.

2023-06-16 20:55 UTC, BrunoSGuima reviewed
Indiquei alguns arquivos a serem revistos.

2023-06-16 20:56 UTC, BrunoSGuima approved these changes

2023-06-16 21:19 UTC, BrunoSGuima reviewed
Indiquei alguns errinhos datilográficos.

2023-06-17 17:24 UTC, akaninja approved these changes
Vou deixar esse aprovado com comentários.

2023-06-17 17:24 UTC, akaninja commented on spec/system/navbar/manager_see_navbar_spec.rb
> +feature 'manager entra no sistema' do
Normalmente esse tipo de teste é desnecessário. Se o projeto tem todos os testes de funcionalidade testados corretamente, todos esses links devem estar sendo testado, já que o teste falharia na ação de clique. Certo? 

Em projetos grandes, os testes chegam a milhares, assim evitamos testes desnecessários como esse.

2023-06-17 17:24 UTC, akaninja commented on spec/system/user_visit_homepage_spec.rb
>  describe 'Visitante navega pela app' do
Parece  um pouco excessivo também adicionar um teste apenas para conferir se há texto "Boas vindas" na tela.

2023-06-17 17:24 UTC, akaninja commented on spec/system/navbar/admin_see_navbar_spec.rb
> +require 'rails_helper'
Esse tipo de testes que apenas verifica presença de links ou textos costuma ser desnecessário. Se o link está presente, ele deve fazer parte de uma funcionalidade. E a gente testa a funcionalidade toda, não apenas verificar se ele está na tela.

2023-06-18 00:03 UTC, merged