Editando departamentos
TreinaDev/GestaoEmpresasTD10 pull request #33
Opened 2023-06-16 17:46 UTC by leanddro

Editando departamentos

Os departamentos são editados apenas pelos Managers (role do usuário), e pertencem a uma empresa. Caso um admin ou employee (roles do usuário) tente criar um departamento, será disparado mensagem de erro 'Usuário sem permissão para executar essa ação'.

2023-06-16 19:28 UTC, BrunoSGuima commented
Tela da edição de departamento e tela de erro na edição.

![edit usuário sem permissão](https://github.com/TreinaDev/GestaoEmpresasTD10/assets/105590450/1e897a40-7d18-45f7-b007-f4f09d076b0e)
![Tela edit departamento erros](https://github.com/TreinaDev/GestaoEmpresasTD10/assets/105590450/e48e9c5c-a17e-48c1-9db8-92a9e96fb406)

2023-06-18 00:19 UTC, sorwalisson commented on spec/models/department_spec.rb
> +      expect(department.errors[:code]).to include 'já está em uso'
Se o código é auto gerado, este teste é realmente necessário?

2023-06-18 00:22 UTC, sorwalisson reviewed
Bom trabalho pessoal, fica só os comentários acima para avaliação!

2023-06-18 00:22 UTC, sorwalisson commented on app/controllers/departments_controller.rb
> +    @companies = Company.all
Se aninha-se a rota de department a company, não seria necessário pegar todas as companies, ja que ela viria pelos parâmetros.

2023-06-18 00:59 UTC, renan-ras commented on app/controllers/departments_controller.rb
> +  before_action :manager?, only: %i[new create edit update]
Essa é uma autenticação comum em vários controllers. Pode ser chamada aqui, mas seu método deveria ficar em ApplicationController.

2023-06-19 13:33 UTC, akaninja commented
Tem alguns comentários abertos ainda. Já foram resolvidos?

2023-06-19 14:01 UTC, BrunoSGuima commented on spec/models/department_spec.rb
> +      expect(department.errors[:code]).to include 'já está em uso'
Este teste verifica que o código é único.

2023-06-19 15:50 UTC, BrunoSGuima commented on app/controllers/departments_controller.rb
> +  before_action :manager?, only: %i[new create edit update]
Alteramos.

2023-06-19 17:40 UTC, BrunoSGuima commented
> Tem alguns comentários abertos ainda. Já foram resolvidos?

Todos já foram resolvidos.

2023-06-20 01:13 UTC, renan-ras commented on app/controllers/departments_controller.rb
>    before_action :authenticate_user!
Esse método já é chamado na ApplicationController

2023-06-20 01:21 UTC, renan-ras commented on app/views/departments/_form.html.erb
> +    <%= form_with model: [@company, @department], local: true, data: { turbo: false } do |f| %>
Só por curiosidade, o que faz '_local: true_'?

2023-06-20 01:34 UTC, renan-ras commented on config/routes.rb
Não tenho certeza, mas acho que não precisa de dois _resources :departments_ nem de _on: :member_. Não poderia ficar assim?

```
resources :departments, only: [:new, :create, :show, :update, :edit] do
  resources :positions, only: %i(new create show edit update)
end
```

2023-06-20 01:40 UTC, BrunoSGuima commented on app/controllers/departments_controller.rb
>    before_action :authenticate_user!
Atualizado

2023-06-20 01:43 UTC, renan-ras commented on spec/request/admin_block_manager_spec.rb
Se eu fosse o André, diria: Não se deve fazer um context só com um it dentro.

```
describe: Bloqueio de manager
  context 'sem sucesso'
    it 'como outro manager'
    it 'como funcionário'
```

2023-06-20 01:44 UTC, BrunoSGuima commented on app/views/departments/_form.html.erb
> +    <%= form_with model: [@company, @department], local: true, data: { turbo: false } do |f| %>
Na realidade não é necessário esse local true. Pois já estamos utilizando o turbo: false. Então eu removi. 
Tivemos uns probleminhas com esse form_with quando alteramos a rota, e fizemos alguns testes. 

O local true especifica se a forma deve ser submetida via AJAX ou não.

2023-06-20 01:46 UTC, renan-ras commented on spec/request/manager_create_departments_spec.rb
> +  context 'Manager tenta criar departamento de outra empresa' do
Muito bom. Precisávamos mesmo desse teste. Ao invés de context podia ser só um it, mas não vou implicar com isso :)

2023-06-20 01:48 UTC, BrunoSGuima commented on spec/request/admin_block_manager_spec.rb
Na realidade mostramos o teste ao Leandro da Rebase e ele aprovou a maneira que escrevemos. Segundo ele, poderíamos colocar a até outro context, caso necessário, para deixar mais explicado. Vou manter assim e questionar ao André depois, mas podemos alterar isso também.

2023-06-20 01:50 UTC, BrunoSGuima commented on spec/request/manager_create_departments_spec.rb
> +  context 'Manager tenta criar departamento de outra empresa' do
Então... Novamente foi como o Leandro da Rebase nos indicou. Uma questão que podemos ver com o André. Acho que pode depender de projeto para projeto.

2023-06-20 01:51 UTC, renan-ras commented on spec/system/department/manager_edit_department_spec.rb
Muito bom, e nem precisaram usar context. :+1:

2023-06-20 01:53 UTC, BrunoSGuima commented on spec/system/department/manager_edit_department_spec.rb
Esse é um teste de sistema, seguimos o padrão que o André nos ensinou. Os anteriores eram testes de request, fizemos conforme dúvidas que tiramos com o Leandro da Rebase.

2023-06-20 01:53 UTC, renan-ras requested changes
Muito bom, só fiquei com algumas dúvidas que apontei em cada arquivo.

2023-06-20 01:54 UTC, sorwalisson commented on app/controllers/application_controller.rb
> +    return if manager.company_id == company_id.to_i
esse company_id.to_i esse .to_i é realmente necessário, acho que o id ja vem em forma de integer n?

2023-06-20 01:56 UTC, sorwalisson approved these changes

2023-06-20 01:59 UTC, renan-ras approved these changes
Boa! :1st_place_medal:

2023-06-20 01:59 UTC, BrunoSGuima commented on config/routes.rb
Já atualizado.

2023-06-20 02:03 UTC, BrunoSGuima commented on app/controllers/application_controller.rb
> +    return if manager.company_id == company_id.to_i
Não. Também achávamos que viria como int, mas vem como string, por isso foi necessária a conversão.

2023-06-20 02:05 UTC, merged